name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions: 
  contents: read
  checks: write
  issues: write
  pull-requests: write
  security-events: write
  statuses: write


jobs:
  Scan:
    uses: rahg0/sl-ci-parent-workflow/.github/workflows/blank.yml@main
    with:
      project_key: slrk
      image_name: raghuesh/vuln-app
      image_tag: latest
    secrets: inherit

